/*
 * SINGULARITY PREDEBUG v2 — AUTO-OPTIMIZED
 * Profile: unroll2x
 * unroll=2 prefetch=0 align=0 hints=0
 * pmc=0 lbr=0 pt=0 batch_msr=0
 * Generated by singularity_predebug_generator
 */

#define _GNU_SOURCE
#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <string.h>
#include <unistd.h>
#include <sys/mman.h>
#include <sys/sysinfo.h>
#include <sys/ioctl.h>
#include <fcntl.h>
#include <linux/perf_event.h>
#include <x86intrin.h>

// ─── Optimization parameters ───
#define UNROLL_FACTOR 2
#define PREFETCH_DIST 0
#define CACHELINE_ALIGN 0
#define BRANCH_HINTS 0
#define BATCH_MSR 0
#define USE_PMC 0
#define USE_LBR 0
#define USE_PT 0

// ─── CPU direct ───
static inline uint64_t rdtsc(void) {
    uint32_t lo, hi;
    asm volatile("rdtsc" : "=a"(lo), "=d"(hi));
    return ((uint64_t)hi << 32) | lo;
}

static inline void clflush(void *addr) {
    asm volatile("clflush (%0)" : : "r"(addr) : "memory");
}

static inline void mfence(void) {
    asm volatile("mfence" : : : "memory");
}

static inline void cpu_pause(void) {
    asm volatile("pause" : : : "memory");
}
static inline void pause_loop(int n) {
    for (int i = 0; i < n; i++) cpu_pause();
}

// ─── MSR access ───
static int msr_fd = -1;
static void init_msr(void) { msr_fd = open("/dev/cpu/0/msr", O_RDONLY); }
static uint64_t read_msr(uint32_t a) {
    uint64_t v = 0; if (msr_fd >= 0) pread(msr_fd, &v, 8, a); return v;
}

// ─── Cache-line aligned thought slot ───
typedef struct __attribute__((packed, aligned(64))) {
    uint16_t aid; uint16_t core; uint32_t cycle;
    float state[32]; uint8_t pad[20];
} slot_t;

int main() {
    printf("SINGULARITY PREDEBUG v2 [unroll2x]\n");
    init_msr();
    slot_t *slot = aligned_alloc(64, 4096);
    memset(slot, 0, 4096);

    float state[32] = {0};
    uint64_t t0 = rdtsc();

    for (uint64_t c = 0; c < 50000; c++) {
        if (c % 1000 == 0) {
            uint64_t therm = 0;
            pread(msr_fd, &therm, 8, 0x19C);
            printf("[%lu] running\n", c);
        }
        slot->aid = (uint16_t)(c & 0xFFFF);
        slot->cycle = (uint32_t)c;
        clflush((void*)slot);
        mfence();
        pause_loop(30);
    }

    double sec = (double)(rdtsc() - t0) / 2.6e9;
    printf("[Done] 50K cycles in 0.00s\n", sec);
    if (msr_fd >= 0) close(msr_fd);
    free(slot);
    return 0;
}
