/*
 * SINGULARITY NOVEL — Generates programs that don't exist yet.
 * Analyzes all existing .c files. Extracts token patterns.
 * Recombines them in novel ways. Compiles. Tests. Keeps the ones that work.
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <dirent.h>
#include <unistd.h>
#include <time.h>
#include <sys/wait.h>

#define MAX_TOKENS 100000
#define MAX_PAIRS 50000
#define MAX_LINE 4096
#define MAX_FILES 256
#define MAX_PROGS 1000

typedef struct { char from[64]; char to[64]; int count; } pair_t;
static pair_t pairs[MAX_PAIRS];
static int n_pairs = 0;

static char *all_tokens[MAX_TOKENS];
static int n_tokens = 0;
static int token_counts[MAX_TOKENS];

// ─── Tokenize a C file ───
static void tokenize_file(const char *path) {
    FILE *f = fopen(path, "r");
    if (!f) return;
    char line[MAX_LINE];
    char prev[64] = {0};
    
    while (fgets(line, sizeof(line), f)) {
        // Simple lexical scan for tokens
        char *p = line;
        while (*p) {
            // Skip whitespace
            while (*p == ' ' || *p == '\t' || *p == '\n') p++;
            if (!*p) break;
            
            // Extract next token (simplified)
            char tok[64]; int ti = 0;
            if (strchr(";{}()=+-*/%&|^<>!.,:", *p)) {
                tok[ti++] = *p++;
                // Handle two-char operators
                if (*p && strchr("=+-*/%&|^<>", *p) && ti == 1) {
                    char c = tok[0];
                    if ((c == '=' && *p == '=') || (c == '!' && *p == '=') ||
                        (c == '<' && *p == '=') || (c == '>' && *p == '=') ||
                        (c == '&' && *p == '&') || (c == '|' && *p == '|') ||
                        (c == '+' && *p == '+') || (c == '-' && *p == '-') ||
                        (c == '-' && *p == '>') || (c == '*' && *p == '*'))
                        tok[ti++] = *p++;
                }
            } else if (*p == '"') {
                tok[ti++] = *p++;
                while (*p && *p != '"') tok[ti++] = *p++;
                if (*p) tok[ti++] = *p++;
            } else if ((*p >= 'a' && *p <= 'z') || (*p >= 'A' && *p <= 'Z') || *p == '_') {
                while ((*p >= 'a' && *p <= 'z') || (*p >= 'A' && *p <= 'Z') ||
                       (*p >= '0' && *p <= '9') || *p == '_') tok[ti++] = *p++;
            } else if (*p >= '0' && *p <= '9') {
                while ((*p >= '0' && *p <= '9') || *p == '.' || *p == 'x' || *p == 'X' ||
                       (*p >= 'a' && *p <= 'f') || (*p >= 'A' && *p <= 'F')) tok[ti++] = *p++;
            } else { p++; continue; }
            tok[ti] = 0;
            
            // Filter noise tokens
            if (ti > 0 && ti < 32 && strcmp(tok, "return") != 0) {
                // Record token
                int found = -1;
                for (int t = 0; t < n_tokens; t++)
                    if (strcmp(all_tokens[t], tok) == 0) { found = t; break; }
                if (found < 0 && n_tokens < MAX_TOKENS) {
                    found = n_tokens;
                    all_tokens[n_tokens] = strdup(tok);
                    n_tokens++;
                }
                if (found >= 0) token_counts[found]++;
                
                // Record transition
                if (prev[0]) {
                    int pfound = -1;
                    for (int p = 0; p < n_pairs; p++)
                        if (strcmp(pairs[p].from, prev) == 0 && strcmp(pairs[p].to, tok) == 0)
                        { pfound = p; break; }
                    if (pfound < 0 && n_pairs < MAX_PAIRS) {
                        strcpy(pairs[n_pairs].from, prev);
                        strcpy(pairs[n_pairs].to, tok);
                        pairs[n_pairs].count = 1;
                        n_pairs++;
                    } else if (pfound >= 0) {
                        pairs[pfound].count++;
                    }
                }
                strcpy(prev, tok);
            }
        }
    }
    fclose(f);
}

// ─── Generate a novel program ───
static void generate_novel(int gen_num, const char *body) {
    char fn[256];
    snprintf(fn, sizeof(fn), "novel_%04d.c", gen_num);
    
    FILE *f = fopen(fn, "w");
    if (!f) return;
    
    fprintf(f, "// novel_%04d - auto-generated by singularity_novel\n", gen_num);
    fprintf(f, "#define _GNU_SOURCE\n");
    fprintf(f, "#include <stdio.h>\n");
    fprintf(f, "#include <stdint.h>\n");
    fprintf(f, "#include <fcntl.h>\n");
    fprintf(f, "#include <unistd.h>\n\n");
    fprintf(f, "static int m;\n");
    fprintf(f, "static void i(void) { m = open(\"/dev/cpu/0/msr\", O_RDONLY); }\n");
    fprintf(f, "static uint64_t r(uint32_t a) { uint64_t v; pread(m, &v, 8, a); return v; }\n\n");
    fprintf(f, "int main() {\n");
    fprintf(f, "    i();\n");
    fprintf(f, "    volatile uint64_t s = 0;\n");
    fprintf(f, "    for (int c = 0; c < 100000; c++) {\n");
    fprintf(f, "        %s\n", body);
    fprintf(f, "        asm volatile(\"\" : : : \"memory\");\n");
    fprintf(f, "    }\n");
    fprintf(f, "    printf(\"done\\n\");\n");
    fprintf(f, "    return (int)(s & 0xFF);\n");
    fprintf(f, "}\n");
    fclose(f);
    
    char cmd[256];
    snprintf(cmd, sizeof(cmd), "gcc -O3 -march=native -o novel_%04d %s 2>/dev/null", gen_num, fn);
    system(cmd);
}

// ─── Generate a novel body from token transitions ───
static char* generate_body(void) {
    static char body[4096];
    body[0] = 0;
    
    // Start with common initial tokens from the training set
    char current[64] = "s";
    int len = 0;
    
    while (len < 20) {  // generate up to 20 tokens
        // Find transitions from current token
        int candidates[MAX_PAIRS], n_cand = 0;
        for (int i = 0; i < n_pairs; i++)
            if (strcmp(pairs[i].from, current) == 0 && strcmp(pairs[i].to, "return") != 0)
                candidates[n_cand++] = i;
        
        if (n_cand == 0) break;
        
        // Pick a random transition, weighted by frequency
        int total = 0;
        for (int i = 0; i < n_cand; i++) total += pairs[candidates[i]].count;
        if (total == 0) break;
        
        int r = rand() % total;
        int selected = candidates[0];
        for (int i = 0; i < n_cand; i++) {
            r -= pairs[candidates[i]].count;
            if (r <= 0) { selected = candidates[i]; break; }
        }
        
        // Append to body
        if (len > 0) strcat(body, " ");
        strcat(body, pairs[selected].to);
        strcpy(current, pairs[selected].to);
        len++;
    }
    
    return body;
}

int main() {
    srand(time(NULL));
    
    printf("SINGULARITY NOVEL\n");
    printf("Learning from %d source files...\n\n", MAX_FILES);
    
    // Scan all .c files
    DIR *d = opendir(".");
    if (!d) return 1;
    struct dirent *de;
    int n_files = 0;
    while ((de = readdir(d))) {
        char *e = strrchr(de->d_name, '.');
        if (!e || strcmp(e, ".c")) continue;
        tokenize_file(de->d_name);
        n_files++;
    }
    closedir(d);
    
    printf("Analyzed %d files\n", n_files);
    printf("Extracted %d unique tokens\n", n_tokens);
    printf("Extracted %d token transitions\n\n", n_pairs);
    
    printf("Most common tokens:\n");
    // Find top 10 tokens
    for (int t = 0; t < 100 && t < n_tokens; t++) {
        if (token_counts[t] > 50)
            printf("  %s: %d\n", all_tokens[t], token_counts[t]);
    }
    printf("\n");
    
    // Generate novel programs
    printf("Generating novel programs...\n\n");
    
    int n_compiled = 0;
    
    for (int g = 0; g < 200; g++) {
        char *body = generate_body();
        
        generate_novel(g, body);
        
        char bin[256];
        snprintf(bin, sizeof(bin), "novel_%04d", g);
        
        if (access(bin, X_OK) == 0) {
            // Test it
            char cmd[256];
            snprintf(cmd, sizeof(cmd), "timeout 2 ./%s > /dev/null 2>&1", bin);
            int run_ok = (system(cmd) == 0);
            
            n_compiled++;
            printf("  [%04d] compiles%s: %s\n", g, run_ok ? " ✓ runs" : " ✗ crashes", body);
            
            // Keep the source if it runs successfully
            if (!run_ok) {
                snprintf(cmd, sizeof(cmd), "rm -f novel_%04d novel_%04d.c", g, g);
                system(cmd);
            }
        } else {
            printf("  [%04d] failed to compile: %s\n", g, body);
            char cmd[256];
            snprintf(cmd, sizeof(cmd), "rm -f novel_%04d.c", g);
            system(cmd);
        }
    }
    
    printf("\nGenerated %d novel programs, %d compiled successfully\n", 200, n_compiled);
    
    // Show the most complex surviving programs
    printf("\nSurviving programs:\n");
    char cmd[256];
    snprintf(cmd, sizeof(cmd), "ls -la novel_*.c 2>/dev/null | head -10");
    system(cmd);
    
    return 0;
}
