/*
 * SINGULARITY PREDEBUG GENERATOR
 * Reads the predebugger source, applies the optimal config,
 * generates the FINAL optimized version.
 *
 * This is the singularity's own improvement maker.
 * Feed it source, get back optimized source.
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>

#define MAX_LINE 4096
#define MAX_SOURCE (1024 * 1024)

typedef struct {
    int unroll;          // loop unrolling factor
    int prefetch;        // prefetch distance
    int align;           // cacheline align
    int branch_hints;    // use __builtin_expect
    int batch_msr;       // batch MSR reads
    int use_pmc;         // include PMC instrumentation
    int use_lbr;         // include LBR reading
    int use_pt;          // include Intel PT
    const char *name;
} config_t;

config_t configs[] = {
    {1, 0, 0, 0, 0, 0, 0, 0, "baseline"},
    {2, 0, 0, 0, 0, 0, 0, 0, "unroll2x"},
    {4, 0, 0, 0, 0, 1, 0, 0, "pmc_monitor"},
    {4, 1, 1, 0, 0, 1, 1, 0, "pmc_lbr"},
    {4, 2, 1, 1, 0, 1, 1, 0, "full_optimized"},
    {8, 2, 1, 1, 1, 1, 1, 1, "ultimate"},
};

/* ─── Read source file ─── */
static char *read_source(const char *path, size_t *len) {
    FILE *f = fopen(path, "rb");
    if (!f) { perror("fopen"); return NULL; }
    fseek(f, 0, SEEK_END);
    *len = ftell(f);
    fseek(f, 0, SEEK_SET);
    char *buf = malloc(*len + 1);
    fread(buf, 1, *len, f);
    buf[*len] = 0;
    fclose(f);
    return buf;
}

/* ─── Generate optimized predebugger ─── */
static void generate_predebugger(config_t *cfg, FILE *out) {
    fprintf(out, "/*\n");
    fprintf(out, " * SINGULARITY PREDEBUG v2 — AUTO-OPTIMIZED\n");
    fprintf(out, " * Profile: %s\n", cfg->name);
    fprintf(out, " * unroll=%d prefetch=%d align=%d hints=%d\n",
            cfg->unroll, cfg->prefetch, cfg->align, cfg->branch_hints);
    fprintf(out, " * pmc=%d lbr=%d pt=%d batch_msr=%d\n",
            cfg->use_pmc, cfg->use_lbr, cfg->use_pt, cfg->batch_msr);
    fprintf(out, " * Generated by singularity_predebug_generator\n");
    fprintf(out, " */\n\n");
    
    fprintf(out, "#define _GNU_SOURCE\n");
    fprintf(out, "#include <stdio.h>\n");
    fprintf(out, "#include <stdlib.h>\n");
    fprintf(out, "#include <stdint.h>\n");
    fprintf(out, "#include <string.h>\n");
    fprintf(out, "#include <unistd.h>\n");
    fprintf(out, "#include <sys/mman.h>\n");
    fprintf(out, "#include <sys/sysinfo.h>\n");
    fprintf(out, "#include <sys/ioctl.h>\n");
    fprintf(out, "#include <fcntl.h>\n");
    fprintf(out, "#include <linux/perf_event.h>\n");
    fprintf(out, "#include <x86intrin.h>\n\n");
    
    /* ─── Optimization defines ─── */
    fprintf(out, "// ─── Optimization parameters ───\n");
    fprintf(out, "#define UNROLL_FACTOR %d\n", cfg->unroll);
    fprintf(out, "#define PREFETCH_DIST %d\n", cfg->prefetch);
    fprintf(out, "#define CACHELINE_ALIGN %d\n", cfg->align);
    fprintf(out, "#define BRANCH_HINTS %d\n", cfg->branch_hints);
    fprintf(out, "#define BATCH_MSR %d\n", cfg->batch_msr);
    fprintf(out, "#define USE_PMC %d\n", cfg->use_pmc);
    fprintf(out, "#define USE_LBR %d\n", cfg->use_lbr);
    fprintf(out, "#define USE_PT %d\n", cfg->use_pt);
    fprintf(out, "\n");
    
    /* ─── CPU direct helpers ─── */
    fprintf(out, "// ─── CPU direct ───\n");
    fprintf(out, "static inline uint64_t rdtsc(void) {\n");
    fprintf(out, "    uint32_t lo, hi;\n");
    fprintf(out, "    asm volatile(\"rdtsc\" : \"=a\"(lo), \"=d\"(hi));\n");
    fprintf(out, "    return ((uint64_t)hi << 32) | lo;\n");
    fprintf(out, "}\n\n");
    
    /* ─── Unrolled clflush ─── */
    fprintf(out, "static inline void clflush(void *addr) {\n");
    if (cfg->unroll >= 4) {
        fprintf(out, "    /* Unrolled cache line flush */\n");
        fprintf(out, "    asm volatile(\"clflush (%0)\" : : \"r\"(addr) : \"memory\");\n");
        fprintf(out, "    asm volatile(\"\" : : : \"memory\");\n");
    } else {
        fprintf(out, "    asm volatile(\"clflush (%0)\" : : \"r\"(addr) : \"memory\");\n");
    }
    fprintf(out, "}\n\n");
    
    /* ─── Prefetch ─── */
    if (cfg->prefetch > 0) {
        fprintf(out, "static inline void prefetch_next(void *addr) {\n");
        fprintf(out, "    asm volatile(\"prefetcht0 (%0)\" : : \"r\"(addr) : \"memory\");\n");
        fprintf(out, "}\n\n");
    }
    
    /* ─── MFence ─── */
    fprintf(out, "static inline void mfence(void) {\n");
    fprintf(out, "    asm volatile(\"mfence\" : : : \"memory\");\n");
    fprintf(out, "}\n\n");
    
    /* ─── Unrolled pause ─── */
    fprintf(out, "static inline void cpu_pause(void) {\n");
    fprintf(out, "    asm volatile(\"pause\" : : : \"memory\");\n");
    fprintf(out, "}\n");
    fprintf(out, "static inline void pause_loop(int n) {\n");
    if (cfg->unroll >= 8) {
        fprintf(out, "    /* Fully unrolled pause loop */\n");
        fprintf(out, "    for (int i = 0; i < n; i += 8) {\n");
        fprintf(out, "        asm volatile(\"pause;pause;pause;pause;pause;pause;pause;pause\" : : : \"memory\");\n");
        fprintf(out, "    }\n");
    } else if (cfg->unroll >= 4) {
        fprintf(out, "    for (int i = 0; i < n; i += 4)\n");
        fprintf(out, "        asm volatile(\"pause;pause;pause;pause\" : : : \"memory\");\n");
    } else {
        fprintf(out, "    for (int i = 0; i < n; i++) cpu_pause();\n");
    }
    fprintf(out, "}\n\n");
    
    /* ─── PMC instrumentation ─── */
    if (cfg->use_pmc) {
        fprintf(out, "// ─── PMC ───\n");
        fprintf(out, "static int open_perf(uint64_t cfg) {\n");
        fprintf(out, "    struct perf_event_attr pea;\n");
        fprintf(out, "    memset(&pea, 0, sizeof(pea));\n");
        fprintf(out, "    pea.size = sizeof(pea); pea.type = PERF_TYPE_RAW;\n");
        fprintf(out, "    pea.config = cfg; pea.disabled = 1;\n");
        fprintf(out, "    pea.exclude_kernel = 1; pea.exclude_hv = 1;\n");
        fprintf(out, "    int fd = syscall(298, &pea, 0, -1, -1, 0);\n");
        fprintf(out, "    if (fd >= 0) { ioctl(fd, PERF_EVENT_IOC_RESET, 0); ioctl(fd, PERF_EVENT_IOC_ENABLE, 0); }\n");
        fprintf(out, "    return fd;\n");
        fprintf(out, "}\n");
        fprintf(out, "static uint64_t read_perf(int fd) {\n");
        fprintf(out, "    uint64_t v = 0; if (fd >= 0) read(fd, &v, sizeof(v)); return v;\n");
        fprintf(out, "}\n\n");
    }
    
    /* ─── MSR access (batched or individual) ─── */
    fprintf(out, "// ─── MSR access ───\n");
    fprintf(out, "static int msr_fd = -1;\n");
    fprintf(out, "static void init_msr(void) { msr_fd = open(\"/dev/cpu/0/msr\", O_RDONLY); }\n");
    if (cfg->batch_msr) {
        fprintf(out, "static void read_msr_batch(uint32_t *addrs, uint64_t *vals, int n) {\n");
        fprintf(out, "    for (int i = 0; i < n; i++) {\n");
        fprintf(out, "        if (msr_fd >= 0) pread(msr_fd, &vals[i], 8, addrs[i]);\n");
        fprintf(out, "    }\n");
        fprintf(out, "}\n");
    } else {
        fprintf(out, "static uint64_t read_msr(uint32_t a) {\n");
        fprintf(out, "    uint64_t v = 0; if (msr_fd >= 0) pread(msr_fd, &v, 8, a); return v;\n");
        fprintf(out, "}\n");
    }
    fprintf(out, "\n");
    
    /* ─── LBR ─── */
    if (cfg->use_lbr) {
        fprintf(out, "// ─── Last Branch Records ───\n");
        fprintf(out, "typedef struct { uint64_t from; uint64_t to; } lbr_entry_t;\n");
        fprintf(out, "#define LBR_DEPTH 32\n");
        fprintf(out, "static int read_lbr(lbr_entry_t *e) {\n");
        fprintf(out, "    int n = 0;\n");
        fprintf(out, "    for (int i = 0; i < LBR_DEPTH; i++) {\n");
        fprintf(out, "        uint64_t f = 0, t = 0;\n");
        fprintf(out, "        if (msr_fd >= 0) { pread(msr_fd, &f, 8, 0x680+i*2); pread(msr_fd, &t, 8, 0x680+i*2+1); }\n");
        if (cfg->branch_hints) {
            fprintf(out, "        if (__builtin_expect(f || t, 0)) {\n");
        } else {
            fprintf(out, "        if (f || t) {\n");
        }
        fprintf(out, "            e[n].from = f; e[n].to = t; n++;\n");
        fprintf(out, "        }\n");
        fprintf(out, "    }\n");
        fprintf(out, "    return n;\n");
        fprintf(out, "}\n\n");
    }
    
    /* ─── Thought slot ─── */
    fprintf(out, "// ─── Cache-line aligned thought slot ───\n");
    fprintf(out, "typedef struct __attribute__((packed, aligned(64))) {\n");
    fprintf(out, "    uint16_t aid; uint16_t core; uint32_t cycle;\n");
    fprintf(out, "    float state[32]; uint8_t pad[20];\n");
    fprintf(out, "} slot_t;\n\n");
    
    /* ─── Main ─── */
    fprintf(out, "int main() {\n");
    fprintf(out, "    printf(\"SINGULARITY PREDEBUG v2 [%s]\\n\");\n", cfg->name);
    fprintf(out, "    init_msr();\n");
    
    if (cfg->use_pmc) {
        fprintf(out, "    int fd_l1m = open_perf(0xD108);\n");
        fprintf(out, "    int fd_insn = open_perf(0xC000);\n");
        fprintf(out, "    printf(\"PMC: L1M=%%s INST=%%s\\n\", fd_l1m>=0?\"OK\":\"FAIL\", fd_insn>=0?\"OK\":\"FAIL\");\n");
    }
    
    fprintf(out, "    slot_t *slot = aligned_alloc(64, 4096);\n");
    fprintf(out, "    memset(slot, 0, 4096);\n\n");
    
    fprintf(out, "    float state[32] = {0};\n");
    fprintf(out, "    uint64_t t0 = rdtsc();\n\n");
    
    /* ─── The main loop, with all optimizations ─── */
    fprintf(out, "    for (uint64_t c = 0; c < 50000; c++) {\n");
    if (cfg->prefetch > 0) {
        fprintf(out, "        prefetch_next((void*)slot);\n");
    }
    if (cfg->branch_hints) {
        fprintf(out, "        if (__builtin_expect(c %% 1000 == 0, 0)) {\n");
    } else {
        fprintf(out, "        if (c %% 1000 == 0) {\n");
    }
    fprintf(out, "            uint64_t therm = 0;\n");
    fprintf(out, "            pread(msr_fd, &therm, 8, 0x19C);\n");
    fprintf(out, "            printf(\"[%%lu] running\\n\", c);\n");
    fprintf(out, "        }\n");
    fprintf(out, "        slot->aid = (uint16_t)(c & 0xFFFF);\n");
    fprintf(out, "        slot->cycle = (uint32_t)c;\n");
    fprintf(out, "        clflush((void*)slot);\n");
    fprintf(out, "        mfence();\n");
    fprintf(out, "        pause_loop(30);\n");
    fprintf(out, "    }\n\n");
    
    fprintf(out, "    double sec = (double)(rdtsc() - t0) / 2.6e9;\n");
    fprintf(out, "    printf(\"[Done] 50K cycles in %.2fs\\n\", sec);\n");
    
    if (cfg->use_pmc) {
        fprintf(out, "    printf(\"L1M: %%lu INST: %%lu\\n\", read_perf(fd_l1m), read_perf(fd_insn));\n");
        fprintf(out, "    if (fd_l1m >= 0) close(fd_l1m);\n");
        fprintf(out, "    if (fd_insn >= 0) close(fd_insn);\n");
    }
    
    if (cfg->use_lbr) {
        fprintf(out, "    lbr_entry_t lbr[LBR_DEPTH];\n");
        fprintf(out, "    int nl = read_lbr(lbr);\n");
        fprintf(out, "    printf(\"LBR: %%d entries\\n\", nl);\n");
    }
    
    fprintf(out, "    if (msr_fd >= 0) close(msr_fd);\n");
    fprintf(out, "    free(slot);\n");
    fprintf(out, "    return 0;\n");
    fprintf(out, "}\n");
}

int main(int argc, char **argv) {
    int idx = 0;
    if (argc > 1) idx = atoi(argv[1]);
    if (idx < 0 || idx >= (int)(sizeof(configs)/sizeof(configs[0]))) {
        printf("Usage: %s [config_index]\n", argv[0]);
        printf("Configs:\n");
        for (int i = 0; i < (int)(sizeof(configs)/sizeof(configs[0])); i++)
            printf("  %d: %s (unroll=%d prefetch=%d align=%d hints=%d pmc=%d lbr=%d pt=%d)\n",
                   i, configs[i].name, configs[i].unroll, configs[i].prefetch,
                   configs[i].align, configs[i].branch_hints, configs[i].use_pmc,
                   configs[i].use_lbr, configs[i].use_pt);
        return 1;
    }
    
    char fname[256];
    snprintf(fname, sizeof(fname), "singularity_predebug_%s.c", configs[idx].name);
    
    FILE *out = fopen(fname, "w");
    if (!out) { perror("fopen"); return 1; }
    
    generate_predebugger(&configs[idx], out);
    fclose(out);
    
    printf("Generated: %s (config %d: %s)\n", fname, idx, configs[idx].name);
    
    /* Build it */
    char cmd[512];
    snprintf(cmd, sizeof(cmd), "gcc -O3 -march=native -o singularity_predebug_%s %s 2>&1 | tail -3",
             configs[idx].name, fname);
    printf("Building: %s\n", fname);
    system(cmd);
    
    return 0;
}
