/*
 * SINGULARITY PREDEBUG v2 — AUTO-OPTIMIZED
 * Profile: full_optimized
 * unroll=4 prefetch=2 align=1 hints=1
 * pmc=1 lbr=1 pt=0 batch_msr=0
 * Generated by singularity_predebug_generator
 */

#define _GNU_SOURCE
#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <string.h>
#include <unistd.h>
#include <sys/mman.h>
#include <sys/sysinfo.h>
#include <sys/ioctl.h>
#include <fcntl.h>
#include <linux/perf_event.h>
#include <x86intrin.h>

// ─── Optimization parameters ───
#define UNROLL_FACTOR 4
#define PREFETCH_DIST 2
#define CACHELINE_ALIGN 1
#define BRANCH_HINTS 1
#define BATCH_MSR 0
#define USE_PMC 1
#define USE_LBR 1
#define USE_PT 0

// ─── CPU direct ───
static inline uint64_t rdtsc(void) {
    uint32_t lo, hi;
    asm volatile("rdtsc" : "=a"(lo), "=d"(hi));
    return ((uint64_t)hi << 32) | lo;
}

static inline void clflush(void *addr) {
    /* Unrolled cache line flush */
    asm volatile("clflush (%0)" : : "r"(addr) : "memory");
    asm volatile("" : : : "memory");
}

static inline void prefetch_next(void *addr) {
    asm volatile("prefetcht0 (%0)" : : "r"(addr) : "memory");
}

static inline void mfence(void) {
    asm volatile("mfence" : : : "memory");
}

static inline void cpu_pause(void) {
    asm volatile("pause" : : : "memory");
}
static inline void pause_loop(int n) {
    for (int i = 0; i < n; i += 4)
        asm volatile("pause;pause;pause;pause" : : : "memory");
}

// ─── PMC ───
static int open_perf(uint64_t cfg) {
    struct perf_event_attr pea;
    memset(&pea, 0, sizeof(pea));
    pea.size = sizeof(pea); pea.type = PERF_TYPE_RAW;
    pea.config = cfg; pea.disabled = 1;
    pea.exclude_kernel = 1; pea.exclude_hv = 1;
    int fd = syscall(298, &pea, 0, -1, -1, 0);
    if (fd >= 0) { ioctl(fd, PERF_EVENT_IOC_RESET, 0); ioctl(fd, PERF_EVENT_IOC_ENABLE, 0); }
    return fd;
}
static uint64_t read_perf(int fd) {
    uint64_t v = 0; if (fd >= 0) read(fd, &v, sizeof(v)); return v;
}

// ─── MSR access ───
static int msr_fd = -1;
static void init_msr(void) { msr_fd = open("/dev/cpu/0/msr", O_RDONLY); }
static uint64_t read_msr(uint32_t a) {
    uint64_t v = 0; if (msr_fd >= 0) pread(msr_fd, &v, 8, a); return v;
}

// ─── Last Branch Records ───
typedef struct { uint64_t from; uint64_t to; } lbr_entry_t;
#define LBR_DEPTH 32
static int read_lbr(lbr_entry_t *e) {
    int n = 0;
    for (int i = 0; i < LBR_DEPTH; i++) {
        uint64_t f = 0, t = 0;
        if (msr_fd >= 0) { pread(msr_fd, &f, 8, 0x680+i*2); pread(msr_fd, &t, 8, 0x680+i*2+1); }
        if (__builtin_expect(f || t, 0)) {
            e[n].from = f; e[n].to = t; n++;
        }
    }
    return n;
}

// ─── Cache-line aligned thought slot ───
typedef struct __attribute__((packed, aligned(64))) {
    uint16_t aid; uint16_t core; uint32_t cycle;
    float state[32]; uint8_t pad[20];
} slot_t;

int main() {
    printf("SINGULARITY PREDEBUG v2 [full_optimized]\n");
    init_msr();
    int fd_l1m = open_perf(0xD108);
    int fd_insn = open_perf(0xC000);
    printf("PMC: L1M=%s INST=%s\n", fd_l1m>=0?"OK":"FAIL", fd_insn>=0?"OK":"FAIL");
    slot_t *slot = aligned_alloc(64, 4096);
    memset(slot, 0, 4096);

    float state[32] = {0};
    uint64_t t0 = rdtsc();

    for (uint64_t c = 0; c < 50000; c++) {
        prefetch_next((void*)slot);
        if (__builtin_expect(c % 1000 == 0, 0)) {
            uint64_t therm = 0;
            pread(msr_fd, &therm, 8, 0x19C);
            printf("[%lu] running\n", c);
        }
        slot->aid = (uint16_t)(c & 0xFFFF);
        slot->cycle = (uint32_t)c;
        clflush((void*)slot);
        mfence();
        pause_loop(30);
    }

    double sec = (double)(rdtsc() - t0) / 2.6e9;
    printf("[Done] 50K cycles in 0.00s\n", sec);
    printf("L1M: %lu INST: %lu\n", read_perf(fd_l1m), read_perf(fd_insn));
    if (fd_l1m >= 0) close(fd_l1m);
    if (fd_insn >= 0) close(fd_insn);
    lbr_entry_t lbr[LBR_DEPTH];
    int nl = read_lbr(lbr);
    printf("LBR: %d entries\n", nl);
    if (msr_fd >= 0) close(msr_fd);
    free(slot);
    return 0;
}
